apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "medik8s.medik8s.io/v1alpha1",
          "kind": "SBDConfig",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "sbd-operator"
            },
            "name": "sbdconfig-sample"
          },
          "spec": {
            "image": "quay.io/medik8s/sbd-agent:latest",
            "imagePullPolicy": "IfNotPresent",
            "iotimeout": "5s",
            "logLevel": "info",
            "nodeSelector": {
              "node-role.kubernetes.io/worker": ""
            },
            "peerCheckInterval": "4s",
            "petIntervalMultiple": 4,
            "rebootMethod": "systemctl-reboot",
            "sbdTimeoutSeconds": 45,
            "sbdUpdateInterval": "3s",
            "sbdWatchdogPath": "/dev/watchdog",
            "sharedStorageClass": "shared-storage-class",
            "staleNodeTimeout": "2h",
            "watchdogTimeout": "60s"
          }
        },
        {
          "apiVersion": "medik8s.medik8s.io/v1alpha1",
          "kind": "SBDRemediation",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "sbd-operator"
            },
            "name": "sbdremediation-sample",
            "namespace": "default"
          },
          "spec": {
            "nodeName": "worker-1",
            "reason": "HeartbeatTimeout",
            "timeoutSeconds": 120
          }
        },
        {
          "apiVersion": "medik8s.medik8s.io/v1alpha1",
          "kind": "SBDRemediationTemplate",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "sbd-operator"
            },
            "name": "sbdremediationtemplate-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2025-11-16T14:09:29Z"
    operators.operatorframework.io/builder: operator-sdk-v1.34.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: sbd-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: SBDConfig is the Schema for the sbdconfigs API.
      displayName: SBDConfig
      kind: SBDConfig
      name: sbdconfigs.medik8s.medik8s.io
      version: v1alpha1
    - description: SBDRemediation is the Schema for the sbdremediations API.
      displayName: SBDRemediation
      kind: SBDRemediation
      name: sbdremediations.medik8s.medik8s.io
      version: v1alpha1
    - description: SBDRemediationTemplate is the Schema for the sbdremediationtemplates
        API.
      displayName: SBDRemediation Template
      kind: SBDRemediationTemplate
      name: sbdremediationtemplates.medik8s.medik8s.io
      version: v1alpha1
  description: TBD
  displayName: SBD
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: sbd-operator
          control-plane: controller-manager
        name: sbd-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/name: sbd-operator
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                app.kubernetes.io/name: sbd-operator
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-bind-address=:8443
                - --leader-elect
                - --health-probe-bind-address=:8081
                command:
                - /manager
                env:
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: controller:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                ports:
                - containerPort: 9443
                  name: webhook-server
                  protocol: TCP
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                volumeMounts:
                - mountPath: /tmp/k8s-webhook-server/serving-certs
                  name: cert
                  readOnly: true
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              serviceAccountName: controller-manager
              terminationGracePeriodSeconds: 10
              volumes:
              - name: cert
                secret:
                  defaultMode: 420
                  secretName: webhook-server-certs
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - sbd
  - storage
  - remediation
  links:
  - name: SBD Operator
    url: https://medik8s.io
  maintainers:
  - email: medik8s@googlegroups.com
    name: Medik8s Team
  maturity: alpha
  provider:
    name: medik8s
  version: 0.0.1
  webhookdefinitions:
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: sbd-operator-controller-manager
    failurePolicy: Fail
    generateName: vsbdconfig.kb.io
    rules:
    - apiGroups:
      - medik8s.medik8s.io
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - sbdconfigs
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-medik8s-medik8s-io-v1alpha1-sbdconfig
