apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    createdAt: "2026-02-08T13:08:43Z"
    operators.operatorframework.io/builder: operator-sdk-v1.33.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
    containerImage: quay.io/medik8s/storage-based-remediation-operator:latest
  name: storage-based-remediation.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - kind: SBDConfig
        name: sbdconfigs.medik8s.medik8s.io
        version: v1alpha1
      - kind: StorageBasedRemediation
        name: storagebasedremediations.medik8s.medik8s.io
        version: v1alpha1
      - kind: StorageBasedRemediationTemplate
        name: storagebasedremediationtemplates.medik8s.medik8s.io
        version: v1alpha1
  description: Storage Based Remediation description. TODO.
  displayName: Storage Based Remediation
  icon:
    - base64data: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wwAAgMBgS+0L8sAAAAASUVORK5CYII="
      mediatype: "image/png"
  install:
    spec:
      deployments:
        - label:
            app.kubernetes.io/managed-by: kustomize
            app.kubernetes.io/name: storage-based-remediation-operator
            control-plane: controller-manager
          name: sbd-operator-controller-manager
          spec:
            replicas: 1
            selector:
              matchLabels:
                app.kubernetes.io/name: storage-based-remediation-operator
                control-plane: controller-manager
            strategy: {}
            template:
              metadata:
                annotations:
                  kubectl.kubernetes.io/default-container: manager
                labels:
                  app.kubernetes.io/name: storage-based-remediation-operator
                  control-plane: controller-manager
              spec:
                containers:
                  - args:
                      - --metrics-bind-address=:8443
                      - --leader-elect
                      - --health-probe-bind-address=:8081
                      - --enable-webhooks=false
                    command:
                      - /manager
                    env:
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: POD_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                    image: quay.io/medik8s/storage-based-remediation-operator:latest
                    livenessProbe:
                      httpGet:
                        path: /healthz
                        port: 8081
                      initialDelaySeconds: 15
                      periodSeconds: 20
                    name: manager
                    readinessProbe:
                      httpGet:
                        path: /readyz
                        port: 8081
                      initialDelaySeconds: 5
                      periodSeconds: 10
                    resources:
                      limits:
                        cpu: 500m
                        memory: 128Mi
                      requests:
                        cpu: 10m
                        memory: 64Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop:
                          - ALL
                securityContext:
                  runAsNonRoot: true
                  seccompProfile:
                    type: RuntimeDefault
                serviceAccountName: sbd-operator-controller-manager
                terminationGracePeriodSeconds: 10
    strategy: deployment
  installModes:
    - supported: false
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - storage-based-remediation
  links:
    - name: Storage Based Remediation
      url: https://storage-based-remediation.domain
  maintainers:
    - email: your@email.com
      name: Maintainer Name
  maturity: alpha
  provider:
    name: Provider Name
    url: https://your.domain
  version: 0.0.1
  minKubeVersion: 1.26.0
