apiVersion: storage-based-remediation.medik8s.io/v1alpha1
kind: StorageBasedRemediation
metadata:
  labels:
    app.kubernetes.io/name: sbr-operator
    app.kubernetes.io/managed-by: kustomize
  name: storagebasedremediation-sample
  namespace: default
spec:
  # Name of the Kubernetes node to be fenced
  nodeName: "worker-1"
  
  # Reason for fencing (optional, defaults to NodeUnresponsive)
  reason: HeartbeatTimeout
