//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SBDConfig) DeepCopyInto(out *SBDConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SBDConfig.
func (in *SBDConfig) DeepCopy() *SBDConfig {
	if in == nil {
		return nil
	}
	out := new(SBDConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SBDConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SBDConfigList) DeepCopyInto(out *SBDConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SBDConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SBDConfigList.
func (in *SBDConfigList) DeepCopy() *SBDConfigList {
	if in == nil {
		return nil
	}
	out := new(SBDConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SBDConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SBDConfigSpec) DeepCopyInto(out *SBDConfigSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.StaleNodeTimeout != nil {
		in, out := &in.StaleNodeTimeout, &out.StaleNodeTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.WatchdogTimeout != nil {
		in, out := &in.WatchdogTimeout, &out.WatchdogTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.PetIntervalMultiple != nil {
		in, out := &in.PetIntervalMultiple, &out.PetIntervalMultiple
		*out = new(int32)
		**out = **in
	}
	if in.IOTimeout != nil {
		in, out := &in.IOTimeout, &out.IOTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.SBDTimeoutSeconds != nil {
		in, out := &in.SBDTimeoutSeconds, &out.SBDTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.SBDUpdateInterval != nil {
		in, out := &in.SBDUpdateInterval, &out.SBDUpdateInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.PeerCheckInterval != nil {
		in, out := &in.PeerCheckInterval, &out.PeerCheckInterval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SBDConfigSpec.
func (in *SBDConfigSpec) DeepCopy() *SBDConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SBDConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SBDConfigStatus) DeepCopyInto(out *SBDConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SBDConfigStatus.
func (in *SBDConfigStatus) DeepCopy() *SBDConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SBDConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SBDConfigValidator) DeepCopyInto(out *SBDConfigValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SBDConfigValidator.
func (in *SBDConfigValidator) DeepCopy() *SBDConfigValidator {
	if in == nil {
		return nil
	}
	out := new(SBDConfigValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SBDRemediation) DeepCopyInto(out *SBDRemediation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SBDRemediation.
func (in *SBDRemediation) DeepCopy() *SBDRemediation {
	if in == nil {
		return nil
	}
	out := new(SBDRemediation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SBDRemediation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SBDRemediationList) DeepCopyInto(out *SBDRemediationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SBDRemediation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SBDRemediationList.
func (in *SBDRemediationList) DeepCopy() *SBDRemediationList {
	if in == nil {
		return nil
	}
	out := new(SBDRemediationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SBDRemediationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SBDRemediationSpec) DeepCopyInto(out *SBDRemediationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SBDRemediationSpec.
func (in *SBDRemediationSpec) DeepCopy() *SBDRemediationSpec {
	if in == nil {
		return nil
	}
	out := new(SBDRemediationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SBDRemediationStatus) DeepCopyInto(out *SBDRemediationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
	if in.NodeID != nil {
		in, out := &in.NodeID, &out.NodeID
		*out = new(uint16)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SBDRemediationStatus.
func (in *SBDRemediationStatus) DeepCopy() *SBDRemediationStatus {
	if in == nil {
		return nil
	}
	out := new(SBDRemediationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SBDRemediationTemplate) DeepCopyInto(out *SBDRemediationTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SBDRemediationTemplate.
func (in *SBDRemediationTemplate) DeepCopy() *SBDRemediationTemplate {
	if in == nil {
		return nil
	}
	out := new(SBDRemediationTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SBDRemediationTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SBDRemediationTemplateList) DeepCopyInto(out *SBDRemediationTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SBDRemediationTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SBDRemediationTemplateList.
func (in *SBDRemediationTemplateList) DeepCopy() *SBDRemediationTemplateList {
	if in == nil {
		return nil
	}
	out := new(SBDRemediationTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SBDRemediationTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SBDRemediationTemplateSpec) DeepCopyInto(out *SBDRemediationTemplateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SBDRemediationTemplateSpec.
func (in *SBDRemediationTemplateSpec) DeepCopy() *SBDRemediationTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(SBDRemediationTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SBDRemediationTemplateStatus) DeepCopyInto(out *SBDRemediationTemplateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SBDRemediationTemplateStatus.
func (in *SBDRemediationTemplateStatus) DeepCopy() *SBDRemediationTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(SBDRemediationTemplateStatus)
	in.DeepCopyInto(out)
	return out
}
